### ISSUE TITLE
cronjob

### ISSUE THREAD

**Issue by msabaeian** [hmralavi/NerkhBackend#3]
the app doesn't need to get last prices from our sources for each API call, it can have cron jobs every 15 minutes (ex: 8:00, 8:15, 8:30, 8:45, 9:00), and store prices in a memory database like [redis](https://redis.io/), we must store latest prices for 1 day to be able to provide diff to yesterday (these arrows  <img width="21" alt="image" src="https://github.com/hmralavi/NerkhBackend/assets/73234920/fca9e3f9-a25e-4eec-a7f6-b65b54d458da">)

<img width="456" alt="image" src="https://github.com/hmralavi/NerkhBackend/assets/73234920/6c909fe8-db54-4e42-9c2a-76c0b1d7087a">

and finally, the `/prices` route can load the last prices from Redis.

I suggest to have a key for each time (00:00, 00:15, 00:30, 00:45, .... 23:30, 23:45) so the insertions would be like:

```
now_time = get_now() # let's imagine it's 9:00
now_prices = await get_prices()

if(redis has key (now_time)){
diff = redis get key now_time - now_prices
write new prices to the key with diff
}else{
write new prices to the key 
}
```

**Comment by hmralavi** [comment]
@msabaeian I'm a bit confused.
which one do we want?
1-always compare the current price with price at yesterday 23:45
2-always compare the current price with price at yesterday at the same time as current time

i think the first one makes more sense. because typically, yesterday's reference price is its closing price (which is 23:45).

**Comment by msabaeian** [comment]
Whatever works for you and requires less effort.
It can also be between yesterdays last price and now, or today’s starting price and now.
Anyway, feel free to choose the easiest option, we can add this to the app manual for our users reference

**Comment by hmralavi** [comment]
Done. now we use github workflow at `.github/workflows/cronjob.yaml` to get bonbast prices and submit them to our server.

**Comment by hmralavi** [comment]
The github actions are not very reliable to consitently update the bonbast prices.
because appearantly, some of github runner IPs are blocked by bonbast API:
https://github.com/SamadiPour/bonbast/issues/29#issuecomment-2064169849
it is still usable because only some of its cronjobs will fail and the other will work.

However, I implemented another solution. i deployed my price updater code on "render.com" and set a cronjob on "cron-job.org".
so for example:
every 5 minutes this url is called: https://nerkh-submitter.onrender.com/update_bonbast
and every 2 hours this url is called: https://nerkh-submitter.onrender.com/update_car

by calling these two urls, the prices at https://nerkh-api-dev.liara.run/ will get updated.

see cronjob status at:
https://22br1bcr.status.cron-job.org/

**Comment by msabaeian** [comment]
@hmralavi Hmm, it's nice but the architecture is getting weird, now there are 3 dependencies only for the prices from Bonbast (GitHub action, Render, and of course the backend itself), this is excessive and I understand all of it is due to Liara servers. I'd say let's find another way to reduce this dependency hell for our future. I see Samadi is using this proxy for his archive app (https://github.com/SamadiPour/rial-exchange-rates-archive/blob/5b65ae474d9f6a1e1d02a8f9bc6e8ecfe96ff674/.github/workflows/daily_update.yml#L39) is that something we can use?

**Comment by msabaeian** [comment]
we can also consider using AWS instead of Liara, an EC2 for FastAPI and Redis and Lambda functions for crawlers

**Comment by hmralavi** [comment]
Nice pick! I'll test the proxy method.

I'm interested to deploy the backend on AWS. it would be a good practice.
if you can setup an account, I'll take care of the rest

**Comment by msabaeian** [comment]
@hmralavi Sure, let me know if the proxy method doesn't go well and I'll create an AWS account

**Comment by hmralavi** [comment]
the proxy method seems to be ok currently.
github cronjob is working well now.

> @hmralavi Hmm, it's nice but the architecture is getting weird, now there are 3 dependencies only for the prices from Bonbast (GitHub action, Render, and of course the backend itself), this is excessive and I understand all of it is due to Liara servers. I'd say let's find another way to reduce this dependency hell for our future. I see Samadi is using this proxy for his archive app (https://github.com/SamadiPour/rial-exchange-rates-archive/blob/5b65ae474d9f6a1e1d02a8f9bc6e8ecfe96ff674/.github/workflows/daily_update.yml#L39) is that something we can use?
